"""add simulator tables

Revision ID: 396fce560f19
Revises: 96ff195c978f
Create Date: 2026-05-23 23:35:43.088459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396fce560f19'
down_revision = '96ff195c978f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulator_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('seeded', sa.Boolean(), nullable=False),
    sa.Column('job_write_test_case', sa.Boolean(), nullable=False),
    sa.Column('job_start_run', sa.Boolean(), nullable=False),
    sa.Column('job_complete_run', sa.Boolean(), nullable=False),
    sa.Column('job_file_bug', sa.Boolean(), nullable=False),
    sa.Column('job_automation_run', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('simulator_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulator_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulator_logs_org_id'), ['org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulator_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulator_logs_org_id'))

    op.drop_table('simulator_logs')
    op.drop_table('simulator_configs')
    # ### end Alembic commands ###
